services:
  app:
    build: ./
    command: ./final-project
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_PASSWORD=secret
  db:
    restart: always
    container_name: library-db
    image: postgres:latest
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-p", "5432"]
  migrate:
    image: migrate/migrate
    links:
      - db
    volumes:
      - ./schema:/schema
    command: ["-path", "./schema", "-database", "postgres://postgres:secret@db:5432/postgres?sslmode=disable", "up"]
    depends_on:
      db:
        condition: service_healthy